version: "3.8"

services:
  kibana:
    # https://www.elastic.co/kibana
    image: docker.elastic.co/kibana/kibana:8.12.2
    hostname: kibana
    container_name: kibana-${COMPOSE_PROJECT_NAME}
    restart: always
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2GB"
    networks:
      - nginxproxy
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      SERVER_HOST: "0.0.0.0"
      XPACK_SECURITY_ENABLED: "false"

networks:
  nginxproxy:
    name: nginxproxy
    driver: bridge