services:

  api:
    build:
      context: ..
      dockerfile: src/CustomerPlatform.Api/Dockerfile
      args:
        VERSION_CORE: ${VERSION_CORE}
    image: customerplatform-api:${VERSION_CORE}
    hostname: api
    container_name: api-${COMPOSE_PROJECT_NAME}
    restart: always
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "4GB"
    networks:
      - nginxproxy
    healthcheck:
      test: [
        "CMD-SHELL",
        "curl -f http://api/health || exit 1"
      ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 2s
    ports:
      - 5000:80
    env_file:
      - env/connectionStrings.otlp.env
      - env/connectionStrings.postgres.env
      - env/connectionStrings.rabbitmq.env
      - env/minio.env
      - env/serilog.env
    volumes:
        # - ../certs:/https:ro
        - data-protection-keys:/home/unet/.aspnet/DataProtection-Keys:rw
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: http://+:80
      # ASPNETCORE_URLS: http://+:80;https://+:443
      # ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/dev-cert.pfx"
      # ASPNETCORE_Kestrel__Certificates__Default__Password: "NetToolsKit.Pass!"
      VIRTUAL_HOST: api
      VIRTUAL_PORT: 80
      Serilog__Properties__Application: "CustomerPlatform.Api"

networks:
  nginxproxy:
  
volumes:
  data-protection-keys: