version: "3.8"

services:
  api:
    image: customerplatform-api:${VERSION_CORE}
    build:
      context: ..
      dockerfile: src/CustomerPlatform.Api/Dockerfile
      args:
        VERSION_CORE: ${VERSION_CORE}
    hostname: api
    container_name: api-${COMPOSE_PROJECT_NAME}
    restart: always
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "4GB"
    networks:
      - nginxproxy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 2s
    ports:
      - "5000:80"
    volumes:
      - data-protection-keys:/home/unet/.aspnet/DataProtection-Keys:rw
    env_file:
      - env/connectionStrings.otlp.env
      - env/connectionStrings.postgres.env
      - env/connectionStrings.rabbitmq.env
      - env/connectionStrings.elasticsearch.env
      - env/minio.env
      - env/serilog.env
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: http://+:80
      VIRTUAL_HOST: api
      VIRTUAL_PORT: 80
      Serilog__Properties__Application: "CustomerPlatform.Api"

networks:
  nginxproxy:
    name: nginxproxy
    driver: bridge

volumes:
  data-protection-keys:
    name: data-protection-keys
