version: "3.8"

services:
  kibana:
    # https://www.elastic.co/kibana
    image: docker.elastic.co/kibana/kibana:8.12.2
    hostname: kibana
    container_name: kibana-${COMPOSE_PROJECT_NAME}
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1GB"
    networks:
      - nginxproxy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsS http://localhost:5601/api/status || exit 1"
        ]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 20s
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      SERVER_HOST: "0.0.0.0"
      XPACK_SECURITY_ENABLED: "false"

networks:
  nginxproxy:
    name: nginxproxy
    driver: bridge