# Global Configuration: Defines the global scrape settings for Prometheus
global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 20s

# Scrape Configurations: Defines the jobs and targets to scrape metrics from
scrape_configs:
  # Prometheus Scrape Configuration: Scrapes metrics from Prometheus server
  - job_name: 'prometheus'
    metrics_path: '/metrics'
    scrape_interval: 15s
    static_configs:
      - targets: ['prometheus:9090']

  # Blackbox Scrape Configuration: Scrapes metrics from the Blackbox Exporter
  - job_name: 'blackbox'
    metrics_path: /probe
    scrape_interval: 15s
    params:
      module: [http_2xx] 
    static_configs:
      - targets:
        - http://prometheus:9090/metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115 

  # Blackbox Exporter Metrics Collection: Collects operational metrics from the Blackbox Exporter
  - job_name: 'blackbox_exporter'
    static_configs:
      - targets: ['blackbox:9115']

  # Node Exporter Scrape Configuration: Scrapes metrics from Node Exporter for host metrics
  - job_name: 'node-exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['node-exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        regex: '([^:]+):\d+'
        target_label: instance
        replacement: '$1'

  # cAdvisor Scrape Configuration: Scrapes metrics from cAdvisor for container metrics
  - job_name: 'containers'
    scrape_interval: 15s
    static_configs:
    - targets: ['cadvisor:8080']

  # Grafana Scrape Configuration: Scrapes metrics from Grafana server
  - job_name: 'grafana'
    metrics_path: '/metrics'
    scrape_interval: 15s
    static_configs:
      - targets: ['grafana:3000']
  
  # Docker Daemon Metrics: Scrapes metrics from the Docker daemon
  - job_name: 'docker-daemon'
    static_configs:
      - targets: ['host.docker.internal:9323']
  
  # OTEL Collector Scrape Configuration: Scrapes metrics from OpenTelemetry Collector
  - job_name: 'otel-collector'
    metrics_path: '/metrics'
    scrape_interval: 15s
    static_configs:
      - targets: ['otel-collector:8889']

  # Tempo Scrape Configuration: Scrapes metrics from Tempo server
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]