services:

  otel-collector:
    # https://opentelemetry.io
    # https://github.com/open-telemetry/opentelemetry-collector-contrib
    image: otel/opentelemetry-collector-contrib:latest
    hostname: otel-collector
    container_name: otel-collector-${COMPOSE_PROJECT_NAME}
    restart: always
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "4GB"
    networks:
      - nginxproxy
    command: [ --config=/etc/otel-collector-config.yaml ]
    ports:
      - 1888:1888     # pprof extension
      - 8888:8888     # Prometheus metrics exposed by the Collector
      - 8889:8889     # Prometheus exporter metrics
      - 13133:13133   # health_check extension
      - 4317:4317     # OTLP gRPC receiver
      - 4318:4318     # OTLP http receiver
      - 55679:55679   # zpages extension
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
      
networks:
  nginxproxy: