services:

  blackbox:   
    # https://prometheus.io
    # https://github.com/prometheus/blackbox_exporter
    image: prom/blackbox-exporter:latest
    hostname: blackbox
    container_name: blackbox-${COMPOSE_PROJECT_NAME}
    restart: always
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "4GB"
    ports:
      - 9115:9115
    command: --config.file=/etc/blackbox/blackbox.yml
    networks:
      - nginxproxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./prometheus/blackbox-config.yml:/etc/blackbox/blackbox.yml:ro
  
  node-exporter:
    # https://prometheus.io
    # https://hub.docker.com/r/prom/node-exporter
    image: prom/node-exporter:v1.9.1
    hostname: node-exporter
    container_name: node-exporter-${COMPOSE_PROJECT_NAME}
    restart: always
    deploy:
      mode: global
      resources:
        limits:
          cpus: "4"
          memory: "4GB"
    networks:
      - nginxproxy
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

  prometheus:
    # https://prometheus.io
    # https://github.com/prometheus/prometheus
    image: prom/prometheus:latest
    hostname: prometheus
    container_name: prometheus-${COMPOSE_PROJECT_NAME}
    restart: always
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "4GB"
    networks:
      - nginxproxy
    extra_hosts:
      - "host.docker.internal=host-gateway"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --storage.tsdb.retention.size=100GB
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-lifecycle
    expose:
      - 9090
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/etc/prometheus
      - prometheus-config:/prometheus
      - /etc/localtime:/etc/localtime:ro
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

networks:
  nginxproxy:

volumes:
  prometheus-data:
  prometheus-config: