version: "3.8"

services:
  otel-collector:
    # https://opentelemetry.io
    # https://github.com/open-telemetry/opentelemetry-collector-contrib
    image: otel/opentelemetry-collector-contrib:0.96.0
    hostname: otel-collector
    container_name: otel-collector-${COMPOSE_PROJECT_NAME}
    restart: always
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "4GB"
    networks:
      - nginxproxy
    command: ["--config=/etc/otel-collector-config.yaml"]
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:13133/ || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "1888:1888"
      - "8888:8888"
      - "8889:8889"
      - "13133:13133"
      - "4317:4317"
      - "4318:4318"
      - "55679:55679"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro

networks:
  nginxproxy:
    name: nginxproxy
    driver: bridge